import { Inter } from "next/font/google";
import "./globals.css"
import Navbar from "./pages/Navbar"
import { Providers } from "./StoreComponents/Providers";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="MainContainer">
          <Providers >
            <div>
              <Navbar />
              {children}
            </div>
          </Providers>

        </div>
      </body>
    </html>
  );
}
